### ISSUE TITLE
[main] Doc issue in file modules/ROOT/pages/os-extensions.adoc: why VIM?

### ISSUE THREAD

**Issue by zhenya-1007** [coreos/fedora-coreos-docs#397] opened 2022-04-15 22:46 UTC
I believe  VIM is an extremely poor example that, if anything, undercuts the pro-containers message the documentation as a whole is trying to make, for these reasons:

-  It's a prototypical user-space program.
- It is _not_ hard to containerize: look at https://github.com/troglobit/mg for an example of editor-in-a-container; [podman documentation](https://docs.podman.io/en/latest/markdown/podman-build.1.html) suggests `--security-opt label=disable` when bind-mounting host's directory into a container.  I suspect you could edit just about any file on the system by running a VIM container, bind-mounting the directory that contains the file, and using the aforementioned `--security-opt label=disable`.
- If one must needs have vim on the machine, it is simple enough to install VIM below /var/usrlocal.  This is something that can be done from a container with a couple of bind-mounts (and potentially with relabeling /var/usrlocal afterwards, as [Redhat's very own documentation for Fedora Server](https://docs.fedoraproject.org/en-US/fedora-server/container-nspawn-install/) suggests.

Please replace VIM with an example that makes sense in the context this page is trying to illustrate. 

Here are some suggestions:
- OpenVPN. Yes, Wireguard is arguably technically superior, but there may be organizations that cannot migrate for a while. 
- An out-of-tree driver. Maybe one of the WiFi cards from BrosTrend (yes, it's a bit silly -- but not nearly as silly as VIM).  Or maybe a driver for a popular optical fibre network adapter? (no idea if all of those are in-tree these days).  Or a GPU driver for AI workloads? (again, no idea if all the popular ones are in-tree these days).  
- NixOS or GNU Guix (again, not the most convincing example -- but _way_ more convincing than VIM, IMO).

**Comment by bgilbert** [comment] 2022-04-15 23:22
Duplicate of #396.

**Closed by bgilbert** 2022-04-15 23:22 UTC
